// Import ESLint's standard JavaScript rules.
import js from "@eslint/js";

// Import browser global-variable definitions.
import globals from "globals";

// Import React Hooks linting rules.
import reactHooks from "eslint-plugin-react-hooks";

// Import React Fast Refresh validation.
import reactRefresh from "eslint-plugin-react-refresh";

// Import TypeScript-aware ESLint rules.
import tseslint from "typescript-eslint";

// Import ESLint flat-configuration helpers.
import {
  defineConfig,
  globalIgnores,
} from "eslint/config";

// Export the complete ESLint configuration.
export default defineConfig([
  // Ignore generated build output.
  globalIgnores(["dist"]),

  {
    // Apply the base rules to TypeScript files.
    files: ["**/*.{ts,tsx}"],

    // Combine JavaScript, TypeScript, React Hooks and Vite rules.
    extends: [
      js.configs.recommended,
      tseslint.configs.recommended,
      reactHooks.configs.flat.recommended,
      reactRefresh.configs.vite,
    ],

    // Configure supported language features.
    languageOptions: {
      ecmaVersion: 2022,
      globals: globals.browser,
    },
  },

  {
    // Apply specific Fast Refresh allowances to generated shadcn files.
    files: [
      "src/components/ui/button.tsx",
      "src/components/ui/badge.tsx",
    ],

    rules: {
      "react-refresh/only-export-components": [
        "error",
        {
          // Permit Vite-compatible constant exports.
          allowConstantExport: true,

          // Permit the variant functions generated by shadcn/ui.
          allowExportNames: [
            "buttonVariants",
            "badgeVariants",
          ],
        },
      ],
    },
  },

  {
    // Allow the theme hook to be exported with ThemeProvider.
    files: ["src/providers/theme-provider.tsx"],

    rules: {
      "react-refresh/only-export-components": [
        "error",
        {
          allowConstantExport: true,
          allowExportNames: ["useTheme"],
        },
      ],
    },
  },
]);