// Import TanStack Query APIs.
import {
  useMutation,
  useQuery,
  useQueryClient,
} from "@tanstack/react-query";

// Import reusable API client.
import {
  apiRequest,
} from "@/lib/api-client";

// Import query keys.
import {
  queryKeys,
} from "@/lib/query-keys";

// Import API models.
import type {
  CloudAccountApiResponse,
  CloudAccountDisconnectApiResponse,
  CloudAccountOnboardingApiResponse,
  CloudAccountRemovalApiResponse,
  CloudAccountSyncQueuedResponse,
  CloudAccountValidationApiResponse,
} from "@/types/api";


// Phase-one AWS registration input.
//
// Security-sensitive IAM values are deliberately absent.
// ExternalId is generated by the backend and Role ARN is
// supplied only during phase two.
export interface CreateCloudAccountInput {
  name: string;

  provider: "aws";

  external_account_id: string;

  enabled_regions: string[];
}


// Phase-two IAM role submission.
export interface UpdateCloudAccountRoleInput {
  accountId: string;

  roleArn: string;
}


// Retrieve registered cloud accounts.
async function getCloudAccounts(): Promise<
  CloudAccountApiResponse[]
> {
  return apiRequest<
    CloudAccountApiResponse[]
  >(
    "/api/v1/cloud-accounts",
  );
}


// Start secure phase-one onboarding.
async function createCloudAccount(
  input: CreateCloudAccountInput,
): Promise<CloudAccountOnboardingApiResponse> {
  return apiRequest<
    CloudAccountOnboardingApiResponse
  >(
    "/api/v1/cloud-accounts",
    {
      method: "POST",
      json: input,
    },
  );
}


// Reload owner/admin-only onboarding material.
async function getCloudAccountOnboarding(
  accountId: string,
): Promise<CloudAccountOnboardingApiResponse> {
  return apiRequest<
    CloudAccountOnboardingApiResponse
  >(
    `/api/v1/cloud-accounts/${accountId}/onboarding`,
  );
}


// Submit the customer IAM Role ARN.
//
// The ExternalId is intentionally impossible to send here.
async function updateCloudAccountRole({
  accountId,
  roleArn,
}: UpdateCloudAccountRoleInput): Promise<CloudAccountApiResponse> {
  return apiRequest<
    CloudAccountApiResponse
  >(
    `/api/v1/cloud-accounts/${accountId}`,
    {
      method: "PATCH",
      json: {
        role_arn: roleArn,
      },
    },
  );
}


// Validate real AWS connectivity through STS.
async function validateCloudAccount(
  accountId: string,
): Promise<CloudAccountValidationApiResponse> {
  return apiRequest<
    CloudAccountValidationApiResponse
  >(
    `/api/v1/cloud-accounts/${accountId}/validate`,
    {
      method: "POST",
    },
  );
}


// Safely disconnect CloudOps provider access.
//
// This deliberately uses POST /disconnect rather than DELETE.
// CloudOps history is retained and customer AWS resources are
// never deleted by this operation.
async function disconnectCloudAccount(
  accountId: string,
): Promise<CloudAccountDisconnectApiResponse> {
  return apiRequest<
    CloudAccountDisconnectApiResponse
  >(
    `/api/v1/cloud-accounts/${accountId}/disconnect`,
    {
      method: "POST",
    },
  );
}


// Permanently remove one CloudOps provider integration.
//
// This deletes CloudOps-owned imported data only.
// It never deletes resources inside the customer's AWS account.
async function removeCloudAccount(
  accountId: string,
): Promise<CloudAccountRemovalApiResponse> {
  return apiRequest<
    CloudAccountRemovalApiResponse
  >(
    `/api/v1/cloud-accounts/${accountId}/remove`,
    {
      method: "POST",
      json: {
        confirmation:
          "REMOVE",
      },
    },
  );
}


// Queue genuine AWS inventory discovery.
async function syncCloudAccount(
  accountId: string,
): Promise<CloudAccountSyncQueuedResponse> {
  return apiRequest<
    CloudAccountSyncQueuedResponse
  >(
    `/api/v1/cloud-accounts/${accountId}/sync`,
    {
      method: "POST",
    },
  );
}


// Query all registered accounts.
export function useCloudAccounts() {
  return useQuery({
    queryKey:
      queryKeys.cloudAccounts
        .all,

    queryFn:
      getCloudAccounts,

    // Worker lifecycle state remains visible automatically.
    refetchInterval:
      5_000,
  });
}


// Create phase-one integration.
export function useCreateCloudAccount() {
  const queryClient =
    useQueryClient();

  return useMutation({
    mutationFn:
      createCloudAccount,

    onSuccess: async () => {
      await queryClient.invalidateQueries({
        queryKey:
          queryKeys.cloudAccounts
            .all,
      });
    },
  });
}


// Load resumable onboarding material on demand.
export function useCloudAccountOnboarding() {
  return useMutation({
    mutationFn:
      getCloudAccountOnboarding,
  });
}


// Store or replace the customer's IAM Role ARN.
export function useUpdateCloudAccountRole() {
  const queryClient =
    useQueryClient();

  return useMutation({
    mutationFn:
      updateCloudAccountRole,

    onSuccess: async () => {
      await queryClient.invalidateQueries({
        queryKey:
          queryKeys.cloudAccounts
            .all,
      });
    },
  });
}


// Validate AWS account mutation.
export function useValidateCloudAccount() {
  const queryClient =
    useQueryClient();

  return useMutation({
    mutationFn:
      validateCloudAccount,

    onSuccess: async () => {
      await queryClient.invalidateQueries({
        queryKey:
          queryKeys.cloudAccounts
            .all,
      });
    },
  });
}


// Safely disconnect one AWS integration.
export function useDisconnectCloudAccount() {
  const queryClient =
    useQueryClient();

  return useMutation({
    mutationFn:
      disconnectCloudAccount,

    onSuccess: async () => {
      await queryClient.invalidateQueries({
        queryKey:
          queryKeys.cloudAccounts
            .all,
      });
    },
  });
}


// Permanently remove one CloudOps AWS integration.
export function useRemoveCloudAccount() {
  const queryClient =
    useQueryClient();

  return useMutation({
    mutationFn:
      removeCloudAccount,

    onSuccess: async () => {
      // Permanent integration removal affects several cached domains.
      // Mark all of them stale so deleted provider data cannot remain
      // presented as current after the destructive operation succeeds.
      await Promise.all([
        queryClient.invalidateQueries({
          queryKey:
            queryKeys.cloudAccounts
              .all,
        }),

        queryClient.invalidateQueries({
          queryKey:
            queryKeys.dashboard
              .summary,
        }),

        queryClient.invalidateQueries({
          queryKey:
            queryKeys.resources
              .all,
        }),

        queryClient.invalidateQueries({
          queryKey:
            queryKeys.costs
              .summary,
        }),

        queryClient.invalidateQueries({
          queryKey:
            queryKeys.budgets,
        }),

        queryClient.invalidateQueries({
          queryKey:
            queryKeys.incidents,
        }),

        queryClient.invalidateQueries({
          queryKey:
            queryKeys.recommendations,
        }),
      ]);
    },
  });
}


// Queue AWS synchronization mutation.
export function useSyncCloudAccount() {
  const queryClient =
    useQueryClient();

  return useMutation({
    mutationFn:
      syncCloudAccount,

    onSuccess: async () => {
      await queryClient.invalidateQueries({
        queryKey:
          queryKeys.cloudAccounts
            .all,
      });
    },
  });
}