apiVersion: v1
kind: Service
metadata:
  name: cloudops-postgres
spec:
  selector:
    app: cloudops-postgres

  ports:
    - name: postgres
      port: 5432
      targetPort: 5432

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cloudops-postgres

spec:
  serviceName: cloudops-postgres

  replicas: 1

  selector:
    matchLabels:
      app: cloudops-postgres

  template:
    metadata:
      labels:
        app: cloudops-postgres

    spec:
      containers:
        - name: postgres

          image: {{ .Values.postgres.image | quote }}

          ports:
            - containerPort: 5432
              name: postgres

          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgres.database | quote }}

            - name: POSTGRES_USER
              value: {{ .Values.postgres.username | quote }}

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.existingSecret }}
                  key: POSTGRES_PASSWORD

          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - {{ .Values.postgres.username | quote }}
                - -d
                - {{ .Values.postgres.database | quote }}

            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - {{ .Values.postgres.username | quote }}
                - -d
                - {{ .Values.postgres.database | quote }}

            initialDelaySeconds: 20
            periodSeconds: 20

          resources:
            requests:
              cpu: 100m
              memory: 128Mi

            limits:
              cpu: 500m
              memory: 512Mi

          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data

  volumeClaimTemplates:
    - metadata:
        name: postgres-data

      spec:
        accessModes:
          - ReadWriteOnce

        resources:
          requests:
            storage: {{ .Values.postgres.storage.size }}