"""add incident source

Revision ID: 185cfe176289
Revises: 4f6382ec938c
Create Date: 2026-08-17 17:49:58.934587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '185cfe176289'
down_revision: Union[str, Sequence[str], None] = '4f6382ec938c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('source', sa.String(length=32), server_default='manual', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'source')
    # ### end Alembic commands ###
