"""add cloudwatch metric samples

Revision ID: 4f6382ec938c
Revises: de4dd8813f24
Create Date: 2026-08-17 17:28:50.184104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f6382ec938c'
down_revision: Union[str, Sequence[str], None] = 'de4dd8813f24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metric_samples',
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('namespace', sa.String(length=128), nullable=False),
    sa.Column('metric_name', sa.String(length=160), nullable=False),
    sa.Column('statistic', sa.String(length=32), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_seconds', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('fk_metric_samples_resource_id_resources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metric_samples')),
    sa.UniqueConstraint('resource_id', 'namespace', 'metric_name', 'statistic', 'timestamp', name='uq_metric_samples_resource_metric_timestamp')
    )
    op.create_index(op.f('ix_metric_samples_metric_name'), 'metric_samples', ['metric_name'], unique=False)
    op.create_index(op.f('ix_metric_samples_resource_id'), 'metric_samples', ['resource_id'], unique=False)
    op.create_index(op.f('ix_metric_samples_timestamp'), 'metric_samples', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metric_samples_timestamp'), table_name='metric_samples')
    op.drop_index(op.f('ix_metric_samples_resource_id'), table_name='metric_samples')
    op.drop_index(op.f('ix_metric_samples_metric_name'), table_name='metric_samples')
    op.drop_table('metric_samples')
    # ### end Alembic commands ###
