"""add aws account validation fields

Revision ID: 609faa46c0b0
Revises: c3e5e67bb413
Create Date: 2026-08-16 16:04:13.035249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '609faa46c0b0'
down_revision: Union[str, Sequence[str], None] = 'c3e5e67bb413'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cloud_accounts', sa.Column('last_validated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('cloud_accounts', sa.Column('last_validation_error', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cloud_accounts', 'last_validation_error')
    op.drop_column('cloud_accounts', 'last_validated_at')
    # ### end Alembic commands ###
