"""add resource lifecycle fields

Revision ID: ba3878dd4345
Revises: 609faa46c0b0
Create Date: 2026-08-16 17:16:48.414629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba3878dd4345'
down_revision: Union[str, Sequence[str], None] = '609faa46c0b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resources', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('resources', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_resources_is_active'), 'resources', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resources_is_active'), table_name='resources')
    op.drop_column('resources', 'deleted_at')
    op.drop_column('resources', 'is_active')
    # ### end Alembic commands ###
