"""create core domain tables

Revision ID: c3e5e67bb413
Revises: 
Create Date: 2026-08-14 14:15:45.247231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c3e5e67bb413'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('budgets',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('scope_type', sa.String(length=32), nullable=False),
    sa.Column('scope_value', sa.String(length=255), nullable=False),
    sa.Column('monthly_limit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('warning_threshold', sa.Integer(), nullable=False),
    sa.Column('critical_threshold', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_budgets_created_by_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_budgets'))
    )
    op.create_table('cloud_accounts',
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('external_account_id', sa.String(length=64), nullable=False),
    sa.Column('role_arn', sa.String(length=512), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('enabled_regions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_cloud_accounts_created_by_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cloud_accounts')),
    sa.UniqueConstraint('provider', 'external_account_id', name='uq_cloud_accounts_provider_external_account_id')
    )
    op.create_table('resources',
    sa.Column('cloud_account_id', sa.UUID(), nullable=False),
    sa.Column('provider_resource_id', sa.String(length=512), nullable=False),
    sa.Column('arn', sa.String(length=1024), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('service', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=160), nullable=False),
    sa.Column('region', sa.String(length=64), nullable=False),
    sa.Column('availability_zone', sa.String(length=64), nullable=True),
    sa.Column('environment', sa.String(length=64), nullable=True),
    sa.Column('owner', sa.String(length=160), nullable=True),
    sa.Column('cloud_state', sa.String(length=64), nullable=False),
    sa.Column('health_state', sa.String(length=32), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cloud_account_id'], ['cloud_accounts.id'], name=op.f('fk_resources_cloud_account_id_cloud_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resources')),
    sa.UniqueConstraint('cloud_account_id', 'provider_resource_id', name='uq_resources_account_provider_resource')
    )
    op.create_index(op.f('ix_resources_cloud_account_id'), 'resources', ['cloud_account_id'], unique=False)
    op.create_index(op.f('ix_resources_health_state'), 'resources', ['health_state'], unique=False)
    op.create_index(op.f('ix_resources_region'), 'resources', ['region'], unique=False)
    op.create_index(op.f('ix_resources_service'), 'resources', ['service'], unique=False)
    op.create_table('cost_records',
    sa.Column('cloud_account_id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('usage_date', sa.Date(), nullable=False),
    sa.Column('service', sa.String(length=160), nullable=False),
    sa.Column('cost_type', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('is_estimated', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cloud_account_id'], ['cloud_accounts.id'], name=op.f('fk_cost_records_cloud_account_id_cloud_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('fk_cost_records_resource_id_resources'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cost_records'))
    )
    op.create_index(op.f('ix_cost_records_cloud_account_id'), 'cost_records', ['cloud_account_id'], unique=False)
    op.create_index(op.f('ix_cost_records_resource_id'), 'cost_records', ['resource_id'], unique=False)
    op.create_index(op.f('ix_cost_records_service'), 'cost_records', ['service'], unique=False)
    op.create_index(op.f('ix_cost_records_usage_date'), 'cost_records', ['usage_date'], unique=False)
    op.create_table('incidents',
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], name=op.f('fk_incidents_assigned_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('fk_incidents_resource_id_resources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incidents'))
    )
    op.create_index(op.f('ix_incidents_resource_id'), 'incidents', ['resource_id'], unique=False)
    op.create_index(op.f('ix_incidents_severity'), 'incidents', ['severity'], unique=False)
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.create_table('recommendations',
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('recommendation_type', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('estimated_monthly_savings', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('risk', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('fk_recommendations_resource_id_resources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendations'))
    )
    op.create_index(op.f('ix_recommendations_resource_id'), 'recommendations', ['resource_id'], unique=False)
    op.create_index(op.f('ix_recommendations_status'), 'recommendations', ['status'], unique=False)
    op.create_table('resource_tags',
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.String(length=1024), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('fk_resource_tags_resource_id_resources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resource_tags')),
    sa.UniqueConstraint('resource_id', 'key', name='uq_resource_tags_resource_key')
    )
    op.create_index(op.f('ix_resource_tags_resource_id'), 'resource_tags', ['resource_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resource_tags_resource_id'), table_name='resource_tags')
    op.drop_table('resource_tags')
    op.drop_index(op.f('ix_recommendations_status'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_resource_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_severity'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_resource_id'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_cost_records_usage_date'), table_name='cost_records')
    op.drop_index(op.f('ix_cost_records_service'), table_name='cost_records')
    op.drop_index(op.f('ix_cost_records_resource_id'), table_name='cost_records')
    op.drop_index(op.f('ix_cost_records_cloud_account_id'), table_name='cost_records')
    op.drop_table('cost_records')
    op.drop_index(op.f('ix_resources_service'), table_name='resources')
    op.drop_index(op.f('ix_resources_region'), table_name='resources')
    op.drop_index(op.f('ix_resources_health_state'), table_name='resources')
    op.drop_index(op.f('ix_resources_cloud_account_id'), table_name='resources')
    op.drop_table('resources')
    op.drop_table('cloud_accounts')
    op.drop_table('budgets')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
