"""add cloud account sync state

Revision ID: de4dd8813f24
Revises: ba3878dd4345
Create Date: 2026-08-16 18:08:25.268953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de4dd8813f24'
down_revision: Union[str, Sequence[str], None] = 'ba3878dd4345'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cloud_accounts', sa.Column('sync_status', sa.String(length=32), server_default='idle', nullable=False))
    op.add_column('cloud_accounts', sa.Column('sync_started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('cloud_accounts', sa.Column('last_sync_error', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cloud_accounts', 'last_sync_error')
    op.drop_column('cloud_accounts', 'sync_started_at')
    op.drop_column('cloud_accounts', 'sync_status')
    # ### end Alembic commands ###
